# Generated by Django 6.0.1 on 2026-01-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=10, help_text='Suits/Saree ke liye master stock'),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
