# Generated by Django 6.0.1 on 2026-01-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_banner_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='active',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.AddField(
            model_name='category',
            name='has_size_option',
            field=models.BooleanField(default=False, verbose_name='Is category mein size hota hai?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('FREE', 'Free Size (Sarees/Unstitched)'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], default='FREE', max_length=10),
        ),
    ]
