# Generated by Django 6.0.1 on 2026-01-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_banner_link_product_color_product_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='has_size_option',
        ),
        migrations.AddField(
            model_name='category',
            name='has_size',
            field=models.BooleanField(default=False, verbose_name='Has Size?'),
        ),
    ]
