# Generated by Django 6.0.1 on 2026-02-14 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. WELCOME100', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coupon_type', models.CharField(choices=[('FLAT', 'Flat Amount (₹)'), ('PERCENTAGE', 'Percentage (%)')], default='PERCENTAGE', max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage coupon ke liye max limit', max_digits=10, null=True)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('limit_per_user', models.IntegerField(default=1, help_text='Ek user kitni baar use kar sakta hai')),
                ('total_usage_limit', models.IntegerField(blank=True, help_text='Puri duniya ke liye total limit (e.g. First 100 users)', null=True)),
                ('times_used', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
