# Generated by Django 6.0.1 on 2026-02-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_wheel_coupon',
            field=models.BooleanField(default=False, help_text='Kya ye coupon Success Page ke Spin Wheel mein dikhana hai?'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='wheel_color',
            field=models.CharField(default='#8B3E48', help_text='Wheel ke us slice ka background color (Hex Code)', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='wheel_label',
            field=models.CharField(blank=True, help_text="Wheel ke slice par kya dikhega? e.g. '10% OFF' ya 'Free Gift'", max_length=50, null=True),
        ),
    ]
