# Generated by Django 6.0.1 on 2026-02-14 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_is_wheel_coupon_coupon_wheel_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='daily_global_limit',
            field=models.IntegerField(default=10, help_text='Ek din mein ye coupon wheel se maximum kitni baar diya ja sakta hai?'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='last_used_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='today_usage_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='win_probability',
            field=models.IntegerField(default=50, help_text='Is coupon ke jitne ka chance kitna hai? (0-100)%. High value = High chance.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
