# Generated by Django 6.0.1 on 2026-02-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_daily_global_limit_coupon_last_used_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='Order ID jiske liye wheel use ho chuka hai', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_won', models.ForeignKey(help_text='User ne kaunsa coupon jeeta tha', on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon')),
            ],
        ),
    ]
